# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My GitHub Blog
email: stephenjjohnson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Not much to see here so far...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: stephenjjohnson
github_username:  stephenjjohnson

# Build settings
markdown: kramdown
